name: Build and Deploy Client and Server

on:
  push:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Node.js for client (React)
      uses: actions/setup-node@v4
      with:
        node-version: '20.12.1'

    - name: Install client dependencies
      run: |
        cd client  # Navigate to client directory
        npm install

    - name: Build the client (React)
      run: |
        cd client
        npm run build
      env: # Idk why they need to be explicitly set again...
        VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
        VITE_SECRET_KEY: ${{ secrets.VITE_SECRET_KEY }}
        VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
        VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
        VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
        VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
        VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}

    - name: Deploy client to server via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.CLIENT_HOST }}
        username: ${{ secrets.CLIENT_USER }}
        password: ${{ secrets.CLIENT_PASSWORD }}
        protocol: ftps
        local-dir: ./client/dist/
        server-dir: /public_html/
        dangerous-clean-slate: true # Unfortunately, errors appear if this is not true. Dangerous but assumed

  build-server:
    runs-on: ubuntu-latest
    needs: build-client  # Ensure server builds after client build

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Bun for server
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install server dependencies (Bun)
      run: |
        cd server
        bun install

    - name: Deploy server via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd cs-prices-website/server
          git pull origin main
          bun install
          bun start
