name: Build and Deploy Client and Server

on:
  push:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Node.js for client (React)
      uses: actions/setup-node@v4
      with:
        node-version: '20.12.1'

    - name: Install client dependencies
      run: |
        cd client  # Navigate to client directory
        npm install

    - name: Build the client (React)
      run: |
        cd client
        npm run build

    - name: Deploy client to server via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.CLIENT_USER }}
        server: ${{ secrets.CLIENT_HOST }}
        ssh_private_key: ${{ secrets.CLIENT_SSH_KEY }}
        port: 22
        local_path: "./client/dist/*"
        remote_path: "/public_html/"
        sftp_only: true
        delete_remote_files: true

  build-server:
    runs-on: ubuntu-latest
    needs: build-client  # Ensure server builds after the client

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Bun for server
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install server dependencies (Bun)
      run: |
        cd server
        bun install

    - name: Deploy server via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22  # SSH port
        script: |
          cd cs-prices-website/server
          git pull origin main
          bun install
          bun start  # Start the server
